eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 8000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    serverapi:
      path: /serverapi/**
      serviceId: eureka-provider
    consumerapi:
      path: /consumerapi/**
      serviceId: ribbon-consumer



